on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      ['stable-3_3_0']
name: ops
jobs:
  ops:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.0
            validate: 'validate'
          - php-version: 7.3
            database: pgsql
            test: 'test'
          - php-version: 7.3
            database: mysql
            test: 'test'
          - php-version: 7.4
            database: pgsql
            test: 'test'
          - php-version: 7.4
            database: mysql
            test: 'test'
          - php-version: 8.0
            database: mysql
            test: 'test'
            SAVE_BUILD: 'save_build'
          - php-version: 8.0
            database: pgsql
            test: 'test'
            SAVE_BUILD: 'save_build'
          - php-version: 8.1
            database: mysql
            test: 'test'
          - php-version: 8.1
            database: pgsql
            test: 'test'
          - php-version: 8.2
            database: mysql
            test: 'test'
          - php-version: 8.2
            database: pgsql
            test: 'test'
    services:
      mysql:
        image: bitnami/mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ops-ci
          MYSQL_PASSWORD: ops-ci
          MYSQL_DATABASE: ops-ci
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    name: ops
    steps:
      - uses: xmlFlow/pkp-github-actions@v1
        with:
          node_version: 12
          dataset_branch: 'stable-3_3_0'
          DATASETS_ACCESS_KEY:  ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: true
